### ISSUE TITLE
minecraftexe site

### ISSUE THREAD

**Issue by bandit0** [VictiniX888/Illegal-Mod-Sites#100]
Today while looking for the camerastudio mod, I found an unlisted site that the URL alone raised red flags to me.
This is the link to the google search for camera studio:
  https://www.google.com/search?q=camera+studio+mod+1.10.2&ie=utf-8&oe=utf-8

The site is called www,minecraftexe,com   I put commas instead of periods to avoid linking to the site.

I fired up VMware Workstation to see how bad it is. 
Host OS: Windows 7 Ultimate 64-Bit
Vmware workstation 11 running Windows XP Professional 64-Bit
Within that VM, I have VMware workstation 9 with a Windows 2000 VM.
Browser:  Firefox version 12 with no adblock installed.
This is what I used to test the site.

Here is what I found.

The site isn't too bad, 
There are ads, though they are of the type found on nearly every site.
(How different the world looks without adblock is incredible)

The Web of Trust report on this site is 50% trustworthiness rating.
A lot of people leave reviews of no trust or suspicious..
WoT Report: https://www.mywot.com/en/scorecard/minecraftexe.com

**Comment by bilde2910** [comment]
I seem to have missed this issue. This site was apparently already listed at the time you made this post, so I'll interpret this as an amendment request instead. I re-reviewed the site, and they unfortunately do seem to have changed over to hosting files themselves now. This puts their redistribution score to 5 (up from 1). Ads rating was also dropped from 5 to 4, as the current level of advertising on the site doesn't meet the requirements for a level 5 rating in this category at this time. Misc remains at 5, following the discovery of a social paywall for downloads, i.e. "like us on social media to unlock the download link". Technically, a paywall that does not require monetary payment, but likes, re-tweets, etc. This is optional, but it's still a scary technique to increase the popularity of the site. The site also tries to entice users to go through this route by labelling the social paywall download as "fast" and the direct links as "slow".
