### ISSUE TITLE
skins-minecraft net

### ISSUE THREAD

**Issue by EmanYm** [VictiniX888/Illegal-Mod-Sites#102]
I did a quick "search this repository" for the site in the title with zero results.

It seem to be a Russian site that offer outdated mods, maps, resource/texture packs and cracked clients on their own urls (the hover-url for Minecraft 1.9.4 is "piratskiy-launcher rar") with no mention of the actual author.
I took a look at a random mod, "Minecraft comes Alive" by WildBamaBoy on curseforge.
On this site, the same mod is named "Mod comes Alive" and has bad English in the description.
I have an ad blocker, and won't even consider turning it off for that site.

Edit:
I noticed a few times the mention of mpegcraft.  Google tells me it redirects to "en-minecraft org" which is listed here.

I think my "favourite" (and I use the term loosely) part of this site is under Tools > Block Launcher

**Comment by bilde2910** [comment]
Thanks for reporting this site. It was indeed found to be in violation of the licenses for a few mods, so it's added to the list. Sorry for the late response to this issue. Thank you again for your contribution!
