### ISSUE TITLE
minecrafthub com

### ISSUE THREAD

**Issue by Winseven4lyf** [VictiniX888/Illegal-Mod-Sites#103]
I happened upon this site from a comment on the Faithful Vanilla pack over on CurseForge, stating that:

> Can you please release this on http;//minecrafthub,com, as the site admin has ripped your description directly from curse. I'm a moderator and will remove the admins post when you make yours!

I took a quick look at this website, and it appears that they also repost mods, which, while (**VERY** rarely) linking to the creator's page, they host the mods on their website, as zip files with no information on which version they are in the file's name.

**Comment by bilde2910** [comment]
Thank you for reporting this site! It violates the license agreement for a few sample mods, so it's been added to the list. The StopModReposts extension server should update shortly. Then, after the next browser restart, your browser will start warning about the site if you've got the extensions installed. :-)
