### ISSUE TITLE
minecraftmodpacks.net

### ISSUE THREAD

**Issue by MJRLegends** [VictiniX888/Illegal-Mod-Sites#104]
This site is reposting mod packs

http://minecraftmodpacks.net/

They are supplying link to download the packs that are old versions, Also most of the packs are out of date versions and not working versions

**Comment by bilde2910** [comment]
I'm sincerely sorry for not getting back to this one. Looking into it now.

**Comment by bilde2910** [comment]
I've added this but didn't find any evidence of reuploads or unofficial downloads on either mods or modpacks. However, as you said, the site misleads users about mods' targeted Minecraft versions. It claims availability of mods for Minecraft 1.13 in page titles, and wrongly labels the target versions of some modpacks (e.g. claims to target 1.7.10, actually targets 1.8.9). Added for that reason, and added a note on the reasoning behind this addition.

If you want me to amend the redistribution score, I'm afraid I'll have to ask for specific examples again. It's on the list now, though. Thanks for the contribution! :-)

**Comment by MJRLegends** [comment]
yeah i think they sorted the evidence of reuploads that i found when making this issue post a few weeks back :D

**Comment by bilde2910** [comment]
Well, that's a good thing :D 

The site will remain listed while it misleads users about version targeting. However, the site owner can also raise an issue here to request their site to be removed from this list, after that issue has been resolved. That doesn't happen often, but it *has* happened in the past, and we'll re-review the site in that case.
