### ISSUE TITLE
www minecraftmods com

### ISSUE THREAD

**Issue by AlexiyOrlov** [VictiniX888/Illegal-Mod-Sites#107]
Seems to be a relatively new website. It provides links to the original mod threads, but also puts direct download links of the mods and their dependencies.

**Comment by bilde2910** [comment]
Hi, and thanks for the submission! Unfortunately, I couldn't find any evidence of redistribution outside of official sources. I reviewed all the mods on the front page, and all of the mods either linked to Curse or to other official download links provided by the developers. As such, I can't accept the site for addition at this time. Feel free to provide one or more specific examples of redistribution on this site if you feel that I might have missed something.
