### ISSUE TITLE
network.vgchartz.com

### ISSUE THREAD

**Issue by MJRLegends** [VictiniX888/Illegal-Mod-Sites#109]
This site is reposting mod packs

http://network.vgchartz.com

They are supplying link to download mods that are not official downloads, Also most of the mods are out of date versions and not working versions

example: http://network.vgchartz.com/extra-planets-mod-1-8-91-7-10-galacticrafts-addon/

this site seems to point to download links from 9minecraft.net

**Comment by bilde2910** [comment]
This should definitely be listed. Thanks for the report! Added.
