### ISSUE TITLE
http://vodafoneuksignal.com is reposting mods.

### ISSUE THREAD

**Issue by ThaumicTom** [VictiniX888/Illegal-Mod-Sites#113]
The site http://vodafoneuksignal.com is reposting mods.

**Comment by VoXaN24** [comment]
Dosn't have any link, is a scam website 
[http://voxgroup.cf/img/up/151092919851cfb3a.png](url)

**Comment by ThaumicTom** [comment]
They are, the download links are from www.files3.minecraft9.net

**Comment by ThaumicTom** [comment]
They are, the download links are from www.files3.minecraft9.net

**Comment by bilde2910** [comment]
Thanks for reporting this site! I've added it to the list; it should propagate to the API and extensions within 5 minutes or so. (A browser restart may be required for the extensions to update their site lists.)
