### ISSUE TITLE
video002 dot com

### ISSUE THREAD

**Issue by EmanYm** [VictiniX888/Illegal-Mod-Sites#114]
Not exactly a download site so I'm not sure if it's a valid report, but this site could potentially be stealing views or money from YouTube creators.

It appears to `wget` video thumbnails and view stats from YouTube.

I haven't clicked on any of them to see if they are working or not.  Could be a virus/trojan or spam machine.

**Comment by VictiniX888** [comment]
I can't access the site, it appears to be down. Can anyone else confirm this?

**Comment by bilde2910** [comment]
I didn't see it before now, but I can't seem to get to it either. It seems like the domain lapsed and is now stuck with the domain registrar.

**Comment by EmanYm** [comment]
You are correct.  The domain is up for sale and the site I mentioned is defaulted to a generic host page.

I can keep half an eye on it to see if it pops up again.

**Comment by EmanYm** [comment]
This address is still going to a "for sale" page.  It seems I may have discovered it just before expiration.
I guess this ticket can be closed and 'rejected'.

**Comment by bilde2910** [comment]
Looks like that, yeah. I'll reject it for now.
