### ISSUE TITLE
minecraftfc.com

### ISSUE THREAD

**Issue by Robijnvogel** [VictiniX888/Illegal-Mod-Sites#115]
Copies mod descriptions from other sites and places mod downloads behind a "subscribe-or-watch-our-ads-generate-revenue-for-a-minute wall".
Proposed line:
| minecraftfc.com                          |      4      |        5       |   1   |       |

See: http://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/mods-discussion/2314237-list-of-sites-stealing-minecraft-content?comment=1616

**Comment by VictiniX888** [comment]
Thanks for reporting this, I've added it to the list. I changed the ad score to 3 instead, because there aren't many ads and they aren't especially obtrusive.

**Comment by Robijnvogel** [comment]
@VictiniX888 however their mod downloads are hidden behind an ad-wall of a minute if people don't want to subscribe to the download service.
