### ISSUE TITLE
http://www.9minecraft.net/

### ISSUE THREAD

**Issue by NoahJelen** [VictiniX888/Illegal-Mod-Sites#116]
I'm not entirely certain, but I think this might be an illegal mod distribution website.

**Comment by NoahJelen** [comment]
I'm going to only use curseforge or the author's minecraft forum thread from now on!

**Comment by bilde2910** [comment]
Thanks for your submission! The site is already on the list - it was actually one of the sites that made us start this project a few years back :-)

CurseForge and Minecraft Forums are both safe places to go to get official download links.
