### ISSUE TITLE
pcminecraft-mods.com

### ISSUE THREAD

**Issue by Yuudaari** [VictiniX888/Illegal-Mod-Sites#118]
pcminecraft-mods.com is providing zip downloads of mods. Here's my mod on there, as an example: https://pcminecraft-mods.com/soulus-mod-minecraft-1-12-2/

**Comment by bilde2910** [comment]
Sorry for the late response! I've added the site to the list. Thanks for your submission. One note though; Soulus mod is licensed under the MIT license. This means that the license of your mod permits the site to upload it and share it as they wish. I did find other mods on the site which do not permit redistribution, however, so the site still qualifies.

**Comment by Yuudaari** [comment]
Oh, thanks, I wasn't even thinking. I use MIT for all my open source stuff and didn't even think about not using it for Soulus. Do you have any licenses you recommend? I read up a bit about other licenses, but can't figure out if any of them do what I want; I want people to be able to use my source code for their own projects, provided their project is reasonably different from mine, but I don't want people to be able to distribute my mod in any way. (No jars, no zip, no source) I wonder if any modders make their own licenses.

**Comment by bilde2910** [comment]
First of all, I am not a lawyer, this is not legal advice, and no words, phrases or other expressions provided herein shall constitute an attorney-client relationship between me and any other third parties, real or imaginary.

Ok, with that out of the way - you may want to take a look at the MMPL version 2, or the Minecraft Mod Public License, whose GitHub repository [is available here](https://github.com/iopleke/MMPLv2). It contains a statement that distribution is reserved for the author as well as any designated distributors directly appointed by the author. It also allows for derivatives, and that these "must contain changes which a reasonably informed person would consider significant".

You're encouraged to read the whole license before applying it to the work, of course. I haven't used or looked into this license myself, but hopefully it can be of help.
