### ISSUE TITLE
minecraft-downloads.com

### ISSUE THREAD

**Issue by Ghalid** [VictiniX888/Illegal-Mod-Sites#121]
Rehosts mods, resource packs, and maps.

Also masquerades the Minecraft Forge page at http://www[dot]minecraft-downloads[dot]com/forge/, as well as hides the Forge download behind a download manager.

**Comment by bilde2910** [comment]
Thank you for the report. I've added it to the list.

- Advertising: 5 (multiple full screen popup ads on download link, ad banners)
- Redistribution: 5 (redistributes mod files)
- Miscellaneous: 4 (outdated mod versions and apparently versions of the mods that don't seem to exist)
