### ISSUE TITLE
blackspigot dot com

### ISSUE THREAD

**Issue by EmanYm** [VictiniX888/Illegal-Mod-Sites#122]
I did a quick ctrl+f on the closed tickets and didn't find this site.

Mods are uploaded by other people.
ChatControlPro on Spigotmc.org - Author kangarko
ChatControlPro on blackspigot - uploaded by McKiroMc
(_Mind you, the version on blackspigot is a full eight months (almost a full major.minor number) version behind the official release...so if you want it free, you don't get recent_)

The site is also behind an anti-adBlocker screen.

**Comment by bilde2910** [comment]
Thanks for the submission.

- Advertisement: 3 (static, unobtrusive banner ads, requires user registration to download)
- Redistribution: 5 (redistributes files)
- Miscellaneous: 3 (not crediting author)
