### ISSUE TITLE
mod-downloader

### ISSUE THREAD

**Issue by DaemonUmbra** [VictiniX888/Illegal-Mod-Sites#128]
Saw a post on the MinecraftForge forums recently about this site mod-downloader[.]com , it copies the look of Optifine and Forge sites, the Optifine side seems to have been harvested by a webcrawler.

I had VirusTotal analyze one of the files this site serves, Malware Alert!
https://www.virustotal.com/en/file/ba02c53c77b09f26dd04192a07e6945fb9bd57a74f87b7195f736f20ba0fdc08/analysis/1524512188/

**Comment by bilde2910** [comment]
The site appears to be down right now. If it comes up again, I can consider adding it.

**Comment by bilde2910** [comment]
Thanks for that link.

There's definitely malware in there. I've added the site, as well as the domain from which the file itself was downloaded, to the list.

Thanks for your contribution :)
