### ISSUE TITLE
minecraftyard.com

### ISSUE THREAD

**Issue by LapisWhovian** [VictiniX888/Illegal-Mod-Sites#130]
Found malware! Unless Dr. Prospector changed his username to "Melissa" all the sudden, this is a repost. Most of the other mods are the same way.
![image](https://user-images.githubusercontent.com/30759261/39671887-c3fca07a-50ee-11e8-97c3-17c9c53260bc.png)

**Comment by bilde2910** [comment]
Hi, thanks for your submission! Minecraftyard is already on the list at this time.

**Comment by bilde2910** [comment]
Actually wait, let me review that for malware too. Hang on.

**Comment by bilde2910** [comment]
I can't find any evidence of malware on the site at first glance. Please link me to the page where you found malware if you can, and I'll change the rating to accommodate for the malware findings.
