### ISSUE TITLE
http://legionminecraft.com/simply-coffee-mod-minecraft/

### ISSUE THREAD

**Issue by VicoLee2000** [VictiniX888/Illegal-Mod-Sites#131]
They are reposting my mod, and others like the Minecraft Transport Mod, using their own downloading site.

**Comment by VicoLee2000** [comment]
I filled in a DMCA form and sent it GoDaddy, which was their host, and they took down the website until they remove my content. I did notice some other re-posted content so this may have to be done again.

**Comment by bilde2910** [comment]
Hi,

Legionminecraft is already listed.

DMCA is currently the best way to deal with reposted mods. Beyond that, there isn't really much we can do, except spread awareness that the sites have pirated content and encouraging mod authors to take action against the sites.
