### ISSUE TITLE
Modpacks?

### ISSUE THREAD

**Issue by coolsquid** [VictiniX888/Illegal-Mod-Sites#23]
Should we add sites redistributing modpacks (with permission from all mod authors, but not the pack author) to the list?

**Comment by VictiniX888** [comment]
Don't we already have sites like that on the list?

**Comment by coolsquid** [comment]
Do we? The reason I ask is because @bilde2910 recieved this: https://puu.sh/gPaiq.png.

**Comment by coolsquid** [comment]
We'll support it.
