### ISSUE TITLE
Possible site to add.

### ISSUE THREAD

**Issue by AssasinAsha** [VictiniX888/Illegal-Mod-Sites#26]
So, there is this site: www minecraftfreemods net
I looked around and there are mods such as Railcraft, Thermal Expansion, VoxelMap and a slew of others, most unknown to me.
Oddly, some are adfly links (which in case of Railcraft don't match the addresses at RC site, so I refuse to go in there) some have mediafire, some have no links at all.
I don't know how to properly check for malware in mods so can't tell you that.
They have at least one account on Minecraft forum trying to ask for permission in broken English(twice so far, seemingly at the same time) but I don't think that's anything positive.

**Comment by Sollace** [comment]
Yup, they're illegally posting mods.

Just one example:
http://www minecraftfreemods net/chameleon-blocks-mod/
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1294507

**Comment by coolsquid** [comment]
@AssasinAsha I removed the direct link from your post.

I have asked CovertJaguar whether he owns the AdFly link in question. I will add the site when he has responded.

**Comment by coolsquid** [comment]
CovertJaguar has confirmed that the links have not been approved by him.

**Comment by AssasinAsha** [comment]
Derp, sorry for not cutting the link, that's embarrassing. Won't do that next time.

**Comment by TeNNoX** [comment]
Chameleon Blocks Mod is mine, and I can confirm, what the site was not authorized to distribute it...
