### ISSUE TITLE
New site to add: minecraft-wiki com

### ISSUE THREAD

**Issue by RedstoneHUD** [VictiniX888/Illegal-Mod-Sites#27]
As I stated on the forum, minecraft-wiki com redirects the user to a fake website scam. Norton (and other systems, I know Norton might not count) have warned me again and again. Please add this site under the note: Malware Alert!

**Comment by VictiniX888** [comment]
Cant access the site, it only takes me to ww38 minecraft-wiki com. Which is basically nothing.

**Comment by coolsquid** [comment]
Closed until more information is provided.

**Comment by bilde2910** [comment]
Redirects to external advertising and scam provider domains for me; tested on multiple IP addresses.
