### ISSUE TITLE
I have left over 30 comments

### ISSUE THREAD

**Issue by SoggyMustache** [VictiniX888/Illegal-Mod-Sites#31]
I have left over 30 comments on this webite http://www.yourminecraft.com/over-crafted-mobs-mod/
Telling them to remove the download and link it to my official curse page i would love to get help as this is anoying AF

**Comment by VictiniX888** [comment]
Really sorry, but there really isn't a way for us to help you with this.
However, one suggestion would be to fiie a DMCA to the site.
More info over here: http://stopmodreposts.org/get-involved/
