### ISSUE TITLE
Sites Reposting My Mods

### ISSUE THREAD

**Issue by JGSBroadcast** [VictiniX888/Illegal-Mod-Sites#34]
These two sites reposted my dessertcraft mod and put screenshots of a completely different mod! They also put direct download links instead of my links through AdFoc.us so I'm losing money. :(

http://www minecraft20 com/
http://minecraftsix com/

Also this site reposted my Obsidian Utilites mod but they put screenshots and videos from a completely different mod also! Also again direct downloads instead of through AdFoc.us The first site even said that my mod was for 1.8.3 but there is no forge for 1.8.3!

http://minecraftside com/
http://www minecraft18 org/

The following site is making money off of my Dessertcraft through AdFly. They also claim them self as the creator.

http://www minecraftdayly com/

This final website reposted my Obsidian Utilities mod taking credit for it and putting a direct download.

http://download-minecraftmods com/

**Comment by VictiniX888** [comment]
Sadly, there's no way for us to help you take down the reposts.
However, you can try filing DMCAs to the sites.
More info over here: http://stopmodreposts.org/get-involved/
