### ISSUE TITLE
8Minecraft

### ISSUE THREAD

**Issue by Eario** [VictiniX888/Illegal-Mod-Sites#36]
8Minecraft is basically a re-branding of 9Minecraft, and according to my research, is being sent out from the same IP Address. It has two websites associated with it, along with a twitter account.
Links to webpages for inspection:
http://www.8minecraft.com/
http://www.8minecraft.org/

**Comment by VictiniX888** [comment]
Both of the sites you've linked are already on the list

**Comment by Eario** [comment]
I was not able to find the list at the time.
Thank you.
