### ISSUE TITLE
Site that is (probably) a malicious duplicate of the minecraft forums

### ISSUE THREAD

**Issue by DataPools** [VictiniX888/Illegal-Mod-Sites#37]
Duplicate of the Minecraft forum and possibly malicious
http://www.eviaxa.com/

**Comment by VictiniX888** [comment]
Hm... not redistributing mods...
I'll let @coolsquid decide on this one

**Comment by coolsquid** [comment]
Yeah, we'll add it.

**Comment by DataPools** [comment]
It is redistributing mods any page on the actual minecraft forum is on this duplicate
