### ISSUE TITLE
www.worldofmods.com is redistrubuting my mod.

### ISSUE THREAD

**Issue by Admicos** [VictiniX888/Illegal-Mod-Sites#38]
I created a mod called Basic Ingame Gui ([Curseforge link for people interested](http://minecraft.curseforge.com/mc-mods/231283-basic-ingame-gui)). Then, while doing some research. I found this site redistrubuting my mod.

I currently don't know if they make money or not (they probably do). But it's pissing me off that there is a lot of sites that redistrubutes mods without permission.

[You can see the stolen link here.](http://www.worldofmods.com/minecraft/mods/4896-basic-ingame-gui-18.html)

Also, i JUST updated the mod. It fixed a crash when joining servers. But since they are distrubuting an old version, people will find from that site, download it and complain to... I don't know, they didn't put any links to contact me.

The only thing i care right now is the Google searches wich show the original link. Updated and supported.

UPDATE: After disabling Adblock for a second or so, i saw a lot of ads. So they ARE monetizing. Now, I'm going to try to contact them to see if i can do some stuff about this.

**Comment by VictiniX888** [comment]
The site is definitely redistributing mods illegally, gonna add it to the list
As for your mod, if contacting them doesn't work, you could try filing a DMCA to them.
You can also report the site to Google, so it doesn't show up in Google searches.

Beyond giving you advice on what to do, there's no way for us to help you
Thanks for contributing :)
