### ISSUE TITLE
minecraft5 net

### ISSUE THREAD

**Issue by DoraJDJ** [VictiniX888/Illegal-Mod-Sites#41]
I was watching a Minecraft mod showcase then founded this illegal website: minecraft5 net.
I looked around and there are some mods like MineMenu, Gravity Gun, AnimalBikes Mod, etc.
And adfly links isn't redirects to official download link, is redirects to mediafire link.
Please check this illegal website and add it to blacklist.

(Sorry for my bad English)

**Comment by VictiniX888** [comment]
Thanks for contributing! Added the site to the list ^^
Also, by the looks of it, there seems to be malware too (seriously, 50MB mods?), so better stay away from it
