### ISSUE TITLE
Wizardhax.com

### ISSUE THREAD

**Issue by Creeperman8362** [VictiniX888/Illegal-Mod-Sites#43]
unblock it pls

**Comment by coolsquid** [comment]
And exactly why should we remove it...?

**Comment by Creeperman8362** [comment]
it helps me find my hacked clients, without it it would be harder.

**Comment by coolsquid** [comment]
Are you kidding? You want us to delist a repost site so that you download cheats without getting a warning? Not gonna happen.

**Comment by Creeperman8362** [comment]
dont judge me on what i download.

**Comment by VictiniX888** [comment]
You have 2 choices here:
1. Don't go to that site
2. Go to that site, and just ignore the warning.

It's just that simple. We're not removing a site that's redistributing mods from the list just so you can save 1 second of clicking "Proceed".

**Comment by Creeperman8362** [comment]
except on every link from within wizardhax.com generates a popup.

**Comment by Sollace** [comment]
@Creeperman8362 
Yet another reason not to use it. And not to take it off the list.

Seriously, just by the game already.

**Comment by Creeperman8362** [comment]
i already have the game dumbass

**Comment by coolsquid** [comment]
No need to be rude, thank you.

**Comment by Creeperman8362** [comment]
no need to make false assumptions as well

**Comment by coolsquid** [comment]
It was a pretty qualified guess considering the site in question distributes hacked clients.
