### ISSUE TITLE
Minecraft 14

### ISSUE THREAD

**Issue by darkhax** [VictiniX888/Illegal-Mod-Sites#46]
I should probably leave a PR, however I am too busy today to fully evaluate the site on my own. They don't seem to mirror downloads (the five downloads I checked were all valid), however they are still reposing various mod threads, and advertising on their download links. I haven't seen any malware on the site, As for advertising, there were only two ads, but they take up roughly 40% of the page, and when I was there, one of them had a naked woman, which isn't really appropriate for a site based on a game that is targeted at random children. This is what I would rate the site, based on my general impression. 

Advertising: 3
Repost: 1
Malware: 1

minecraft14.com

**Comment by VictiniX888** [comment]
Hm... well that site isn't reposting mods, so...
I'm leaning towards not adding it to the list
Wonder what @coolsquid thinks
Closing this for now
