### ISSUE TITLE
MinecraftEz looks like it's reposting using Mega

### ISSUE THREAD

**Issue by mcrocks999** [VictiniX888/Illegal-Mod-Sites#51]
Here ya go: http://minecraftez.net/

**Comment by bilde2910** [comment]
Thanks for reporting; the site has been added to the list!

**Comment by minecrafteznet** [comment]
Hi! I is admin minecraftez.net! 
Im so sorry for it! I will delete Mega and will update again link! Thank you report! Thank!

**Comment by mcrocks999** [comment]
You realise, the point of this is to take down your site or at least stop people using your site.
LINK the downloads to the original threads. NOT your own reuploads.

**Comment by minecrafteznet** [comment]
Thank you again!
I understand!! I will remove it! and i don't reuploads again! 
Thanks You So Much

**Comment by mcrocks999** [comment]
Not really sure why you'd be thanking for a report against you, but ok... xd

**Comment by minecrafteznet** [comment]
So! because! I want it better :D Have nice day pro :D

**Comment by VictiniX888** [comment]
@minecrafteznet Thanks for changing the download links! Really appreciate it!
I'll remove your site from the list in a moment

**Comment by minecrafteznet** [comment]
@VictiniX888 Thank you! Have Nice Day Bro :D
