### ISSUE TITLE
FDMINECRAFT.NET

### ISSUE THREAD

**Issue by xJon** [VictiniX888/Illegal-Mod-Sites#52]
Link -> http://fdminecraft.net/
It's currently not blacklisted, and it redistributes tons of mods (Including [mine](http://fdminecraft.net/useless-mod/)), and more.
My AdBlock says it blocked 6 ads in one page.
Didn't found misleading information.
Thanks.

**Comment by bilde2910** [comment]
Thanks for reporting; the site has been added to the list!

**Comment by xJon** [comment]
Thanks @bilde2910 :)
Good to see you here!

**Comment by bilde2910** [comment]
Good to see you too, @xJon! Just doing my part in keeping the web clean :)
