### ISSUE TITLE
CraftHD.net

### ISSUE THREAD

**Issue by xJon** [VictiniX888/Illegal-Mod-Sites#54]
> Link -> *http://www.crafthd.net/*
It's currently not blacklisted, and it redistributes tons of mods (Including [mine](http://www.crafthd.net/useless-mod/)), and more.
My AdBlock says it blocked *2* ads in one page.
Didn't found *much information at all, so not much misleading info*.
Thanks.

**Comment by VictiniX888** [comment]
Added it to the list, thanks for contributing ^^
