### ISSUE TITLE
http://www.5minecraft.com

### ISSUE THREAD

**Issue by xJon** [VictiniX888/Illegal-Mod-Sites#56]
> Link -> *http://www.5minecraft.com/*
It's currently not blacklisted, and it redistributes tons of mods (Including [mine](http://www.5minecraft.com/useless-mod/)), and more.
My AdBlock says it blocked *2* ads in one page.
Didn't found *much information at all, so not much misleading info*.
Thanks.

**Comment by VictiniX888** [comment]
Man, that URL looks so familiar...
Anyways, added it to the list, thanks for contributing!
