### ISSUE TITLE
minecraftyard.com

### ISSUE THREAD

**Issue by mezzodrinker** [VictiniX888/Illegal-Mod-Sites#57]
It appears that [minecraftyard.com](http://minecraftyard.com/) reposts especially popular mods (including - but not limited to - [Minecraft Comes Alive](http://www.minecraftyard.com/minecraft-comes-alive-mod/), [TooManyItems](http://www.minecraftyard.com/toomanyitems/) and the [GLSL Shaders Mod](http://www.minecraftyard.com/shaders-mod/)), resource packs (for example [Sphax' PureBDCraft](http://www.minecraftyard.com/sphax-purebdcraft/) and [Misa's Realistic Resource Pack](http://www.minecraftyard.com/misas-realistic-resource-pack/)) and [Minecraft Forge](http://www.minecraftyard.com/forge-api-jar/).

Most (if not all) pages on minecraftyard.com...
* contain faked mod banners and screenshots with "MinecraftYard.com" added to them,
* provide download links to files mirrored on their own server or AdF.ly links that are not the official ones,
* do not credit the respective owners,
* contain few ads (according to AdBlock Plus at least one per page),
* advertise the reposted mod as compatible with the latest versions (such as Forge mods for 1.9, ha ha) and
* provide outdated versions.

I personally do not own any of the mentioned mods/resource packs, but at least for Minecraft Comes Alive, I can assure that all above claims but the very first are true.

**Comment by VictiniX888** [comment]
They seem to link to both the original download and their own mirror. Hm...
Ironically, at the end of every post they put something like "we have checked all these files with an antivirus" "we want to stop fake links and malicious stuff"

Maybe I could ask the owner to take down the alt downloads

**Comment by mezzodrinker** [comment]
Maybe you could, yes. The question is how likely will a response be? If you want to give it a try, though, you can check the [Privacy Policy](http://www.minecraftyard.com/privacy-policy/) (a pretty strange place to write down a contact email, if you ask me) or use the provided [Contact Form](http://www.minecraftyard.com/contact-me/). There's no About page anywhere to be found, which makes the site and its intentions even more questionable. If you try taking a look at the admin's profile (named "Melissa", the only WordPress profile you'll find there), it will just redirect you straight back to the main page.

**Comment by VictiniX888** [comment]
Ah, the privacy policy page, didn't check that. I did see the Contact Form though, but I would prefer being able to email. Let's see how long it takes for them to reply

**Comment by mezzodrinker** [comment]
Have fun waiting.

**Comment by VictiniX888** [comment]
Lemme see... I give them 2 days before I put the site on the list

**Comment by mezzodrinker** [comment]
That sounds fairly reasonable.

**Comment by mezzodrinker** [comment]
So... Has there been any response yet?

**Comment by VictiniX888** [comment]
Didn't work, bah, I'll just put it on the list.
