### ISSUE TITLE
http://revozin.com/

### ISSUE THREAD

**Issue by xJon** [VictiniX888/Illegal-Mod-Sites#58]
> Link -> *http://revozin.com/*
It's currently not blacklisted, and it redistributes about 200 of mods (Including [mine](http://revozin.com/useless-mod/)), and more.
My AdBlock says it blocked *1* ad in one page.
*Actually has some useful information, along original writing.*
Thanks.

**Comment by VictiniX888** [comment]
Gonna add it to the list, thanks ^^
