### ISSUE TITLE
resourcepack net

### ISSUE THREAD

**Issue by zxinmine** [VictiniX888/Illegal-Mod-Sites#59]
A resource pack re-posting website, shows classic illegal mod site signs.
I would take precautions before downloading anything.

**PROCEED WITH CAUTION**
Link: resourcepack.net
~zxin

**Comment by VictiniX888** [comment]
Bah, being cautious isn't me
Antivirus saves the day XP

But even though the title is misleading (MC1.9 strikes back), the downloads are the original links, so nothing illegal here

**Comment by Robijnvogel** [comment]
@VictiniX888 
Please take a look at:
http://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/mods-discussion/2314237-list-of-sites-stealing-minecraft-content?page=78#c1641

Does them "cutting out the middle man" in this case, addfly, make them a reposting site?

**Comment by bilde2910** [comment]
If they are still using the original download links then no, per [our current definitions](https://github.com/VictiniX888/Illegal-Mod-Sites/blob/master/HOWTO.md) it would not make them a reposting site. But it would count towards the miscellaneous rating, and depending on the level of advertising on the site, it might qualify for addition if a high miscellaneous rating is combined with a high advertising score.
