### ISSUE TITLE
4minecraft.com

### ISSUE THREAD

**Issue by darkhax** [VictiniX888/Illegal-Mod-Sites#62]
I was going to make a PR for this entry, however I wasn't sure what files I need to edit. There were three site files, however the json and txt versions don't seem to be updated so frequently. I would appreciate it if someone could explain which files to edit so I can do that in the future. Now, onto 4minecraft.com....

The site has a lot of advertising, including ads which open up into new tabs. I recently got an add which attempted to install spyware on my system, and attempted to phish my information. (It also tried to make my screen BSOD but it failed miserably. Images below :p). Because of this, I would give a **5 for advertising**. 

The site seems to have posts generated by the user base, along with posts made by the site team. They majority of the stolen mods seem to be from the site themselves, as the download links use their own domain, however I could not find a link which pointed to an unofficial source. There were some downloads which point to sites like mediafire, so it is difficult to confirm whether or not they're actually redistributing the mods. I would like to give the site a **2 for redistribution however based on the guidelines it might be a 1**. 

The site gives credit to the original author, and the versions are mostly correct. It does bypass the original posters ad wall in some situations, and almost all of their downloads are not up to speed with the original source. I would give it a **2 for misc** although I think it deserves a +1 for all the horrible ads, adware and spyware. It also blocks adblock users. 

![image](https://cloud.githubusercontent.com/assets/2250798/11544165/a6ea3b4c-98fd-11e5-8ac9-6095c3f507e2.png)

Edit: Over the course of writing this report, I have encountered several ads like the one in the image above. I think that adware/spyware/malware should be included in the extra info section for this site. The site also serves ads which are not family safe (affair ads, sex ads and so on). I don't know if that's something this list cares about documenting, if it is I think that this should also be noted in the extra info section.

**Comment by VictiniX888** [comment]
When I add in new sites I tend to edit all 3 of the files. Although if you just edit the markdown file, I'll go and edit the others anyways.
I put 1 for redistribution as they aren't really redistributing them, and in fact link to official downloads.
I also put in a note about malware alert.

Thanks for contributing ^^

**Comment by Sollace** [comment]
The site sees kind of familiar. Doesn't the list already have domains like 9mineraft, 6minercaft, etc on it?

If so I'd wager that these are the same guys and a regex entry like "[1234567890]*minecraft\.*" might be good for catching all the variants.
