### ISSUE TITLE
Issue with the 9minecraft and the other site

### ISSUE THREAD

**Issue by MatthewStevenGo** [VictiniX888/Illegal-Mod-Sites#69]
I discovered the issue here: http://www.9minecraft.net/minecraft-1-10-official-download/

which is that it distributes the Minecraft version without the permission of Mojang.

Also, minecrafthut.com is at best the mod-stealing site that distributes mods and maps without prior permission of the author and at worst distributes hacked clients and mods.

**Comment by bilde2910** [comment]
Thank you for reporting! 9minecraft is already on the list, but minecrafthut wasn't, so it has been added. :)
