### ISSUE TITLE
Add also revozin.com

### ISSUE THREAD

**Issue by MatthewStevenGo** [VictiniX888/Illegal-Mod-Sites#70]
http://revozin.com/download-flans-mod/

Just discovered the stolen Flans mod in revozin.com.

**Comment by bilde2910** [comment]
Hi again! Thank you for all the site reports you are providing; they're of great help! Revozin is already on the list, though. :-)

**Comment by MatthewStevenGo** [comment]
Thanks. I didn't see it. sorry :)
