### ISSUE TITLE
Evaluation of MCPE Universe

### ISSUE THREAD

**Issue by bilde2910** [VictiniX888/Illegal-Mod-Sites#72]
Reported on IRC as hosting "bad old versions, for versions that are old", will look into seeing if it infringes any copyright. Needs a review, claims to be a community site.

**Comment by VictiniX888** [comment]
I did look into it just now while looking at mcpedl, and I think it's pretty much like planetminecraft - it's a community site, but there are people who will redistribute other's mods.

E.g. Pocket Puppies:
[Original](http://mcpeuniverse.com/mods/pocket-puppies-0-5-4/) - links to his own Github website
[Repost](http://mcpeuniverse.com/mods/pocket-puppies-mod/) - by another person, links to a file-sharing site

Imo it shouldn't be on the list as modders do upload to the site, even though there are a few reposts here and there

**Comment by bilde2910** [comment]
Will leave it off the site for now, but will keep an eye on it. We're currently discussing a bunch of MCPE sites in EsperNet/#stopmodreposts, do you want to join in?
