### ISSUE TITLE
What is the known good mod source?

### ISSUE THREAD

**Issue by bk5115545** [VictiniX888/Illegal-Mod-Sites#73]
I was led to the website and consequently this repository by a link on the below Forge forum.
http://www.minecraftforge.net/forum/index.php/topic,41463.0.html?PHPSESSID=5a4ba66gl0cm7dpldv906mtt61

I'm glad this list exists but is it possible to list the known good source(s) on either the website or, if there are a few, then in a table similar to the known bad sources?

A friend asked me to put together a modpack for him but I'm not sure where to get the mods.  The list makes it clear which sites to avoid but where should I go to get the mods?

**Comment by VictiniX888** [comment]
Well first of all, hello :)

One of the best sources for mods is [Curse](https://mods.curse.com/mc-mods/minecraft). Most mod authors upload their own mods on there, and there's a system in place which doesn't allow for reposts and malware.

You can also find mods on the [official forums](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods).

Other than those, planetminecraft.com is also a community site where moddes upload their own mods, but it has less mods than both Curse and the forums
