### ISSUE TITLE
Potential Reuploader

### ISSUE THREAD

**Issue by mandm635** [VictiniX888/Illegal-Mod-Sites#76]
http://minecraftsix.com/

**Comment by VictiniX888** [comment]
minecraftsix is not reposting mods, as it links to the original downloads.
minecraftfive is already on the list, so no need to add it again :p 
mcpedl was reported not too long ago ( #71 ) , and we came to the conclusion that it is a legitimate site.
shadersmods also link to original downloads, so it's not illegal

legacymodpack seems to be reposting and rebundling mods though, as it downloads an entire zip file of mods from a single URL. I'll add that to the list.
Thanks for contributing :)
