### ISSUE TITLE
Rate unrated sites

### ISSUE THREAD

**Issue by VictiniX888** [VictiniX888/Illegal-Mod-Sites#8]

**Comment by VictiniX888** [comment]
www gamespot com/profile/JayMine109/
This user seems to be redistributing mods

**Comment by HanFox** [comment]
Gamespot itself isn't technically a bad site, it's the fact their forum is littered with spam.

Basically do a Google search for a mod and it'll pop-up on their forum with links to one or two or more of the sites you have in your "bad list".

Gamespot in general should just be avoided when it comes to MC.

![Example search](http://puu.sh/e3lyn/2abab22ca2.png)

**Comment by coolsquid** [comment]
Close #8
