### ISSUE TITLE
Italiano is lowercase

### ISSUE THREAD

**Issue by deframet** [VictiniX888/Illegal-Mod-Sites#80]
![img_20160909_093745](https://cloud.githubusercontent.com/assets/18748569/18379160/342522e6-7671-11e6-9154-d3d0e0abb749.jpg)

**Comment by bilde2910** [comment]
Hi again! This is actually controlled by Google and Opera on their respective add-on stores, and is outside our ability to fix. The name of the language itself is not present anywhere in the extension's source code. Sorry about that, but thanks for the report regardless!

**Comment by deframet** [comment]
Ok, thank you for the reply.
