### ISSUE TITLE
3 Stealing Sites

### ISSUE THREAD

**Issue by d4rkstar00** [VictiniX888/Illegal-Mod-Sites#81]
This websites uploaded my own mods...
http://www.minecraftxz.com/
http://mmoct.eu/ (See this: http://mmoct.eu/forum654/)
http://craftdl.ru/

**Comment by VictiniX888** [comment]
Sorry for the late response, but anyways:

minecraftxz is a Chinese reposting site. I just happen to know Chinese so I read through some of the pages, and while they do repost the mods, all of them also link to the minecraftforums post, and they add a note saying they recommend those not in China to download from the original site. I'll still be adding the site to the list.

mmoct.eu's posts all link to craftdl.ru, which in turn links to Curse's downloads, so they're fine.
