### ISSUE TITLE
Russian Sites Stole My Map

### ISSUE THREAD

**Issue by OfficialRaider** [VictiniX888/Illegal-Mod-Sites#82]
http://ru-minecraft.ru/karty-dlja-minecraft/43078-pvp-karta-jpprb-custom-pvp.html

http://ru-m.org/karty-minecraft/13760-skachat-jpprb-custom-kit-pvp-dlya-minecraft.html

Here is one of my official uploads. http://www.minecraftforum.net/forums/mapping-and-modding/maps/2499775-jpprb-custom-kit-pvp As you can see the site with the working download watermarked my images and I cant read anything about it :( thanks for any possible help! -Raider
Note: It sucks even more because if people download from there they don't get the texture pack :(

**Comment by bilde2910** [comment]
Hi, OfficialRaider! These sites are both alreay on the list. As for removing your mod from there - there is very little you can do, really, as these sites are in Russia. If they were US-based, you could send a DMCA notice, and many other countries also take things down when properly requested. I'm afraid I can't really do much more here :(

**Comment by OfficialRaider** [comment]
Darn. Thanks for the answer :) And my apologies, I was unaware there was a list xD please forgive me. Thanks again! -Raider

**Comment by bilde2910** [comment]
No problem! The list is available [right here](https://github.com/VictiniX888/Illegal-Mod-Sites/blob/master/SITES.md) for future reference :)
