### ISSUE TITLE
Auto-generate JSON and TXT

### ISSUE THREAD

**Issue by bilde2910** [VictiniX888/Illegal-Mod-Sites#83]
I can set up a PHP script on my server that grabs the markdown version of the list from GitHub and auto-generates a JSON or text file based on it. I figure this may save us a lot of time because we'd only have to update one file instead of three, and it allows us to extend to new formats like XML or even NBT. Plus, it can be queried directly from clients that need this data, and it will always be up to date. Thoughts, @VictiniX888, @coolsquid ?

**Suggestion:** Discontinue JSON, TXT from repository to redelegate them to an external API service

**Comment by VictiniX888** [comment]
This is more efficient than what we have now, and also since most people only view the markdown list, so I guess you can take the JSON and text files from the repo.

+1

**Comment by bilde2910** [comment]
API has been implemented and JSON and TXT files removed from repository.

**Comment by bilde2910** [comment]
I added documentation for the API to the [wiki](https://github.com/VictiniX888/Illegal-Mod-Sites/wiki/API-access-and-formats).
