### ISSUE TITLE
Domain name ownership

### ISSUE THREAD

**Issue by bilde2910** [VictiniX888/Illegal-Mod-Sites#85]
The Stop Mod Reposts domain name stopmodreposts.org is not resolving. I propose the domain's ownership be transferred to either me or @coolsquid for maintenance.

CC: current registrant @jakimfett, please answer if possible.

**Comment by jakimfett** [comment]
Fixed. Sorry 'bout that, was messing with DNS stuff and that site didn't get properly updated.
