### ISSUE TITLE
Reuploading Sites

### ISSUE THREAD

**Issue by d4rkstar00** [VictiniX888/Illegal-Mod-Sites#89]
http://www.wdsj2.com/
Example: http://www.wdsj2.com/game/3558.html The download is hosted from their website.

http://www.mcmap.cc/
Example: http://www.mcmap.cc/Minecraft/mod/1710/3979.html Download is hosted on some other website.

http://mc.ahgame.com/
Example: http://mc.ahgame.com/mod/20170210186856.shtml Downloads are hosted from their website.

**Comment by VictiniX888** [comment]
The sites have been added to the list. Thanks for contributing!
