### ISSUE TITLE
Technic Launcher.

### ISSUE THREAD

**Issue by smaltin-rules** [VictiniX888/Illegal-Mod-Sites#90]
Technic Launcher (https://www.technicpack.net/) has some mod pack owners that redistribute mods and get away with it. I do believe that technic launcher overall is a good website, but the mod pack content has certain mods redistributed into the pack without the owner's approval.

EDIT: I never knew you were all so harsh with those thumb down's. Jeez.

**Comment by camatthew** [comment]
there is a report button for just that
