### ISSUE TITLE
Minecraftdownload.in

### ISSUE THREAD

**Issue by NOPEname** [VictiniX888/Illegal-Mod-Sites#91]
One of my maps got reposted (with a new download with ads) on this website: 
https://minecraftdownload.in/

Probably all content on that webiste is reposted with new downloads.

**Comment by bilde2910** [comment]
Hi @NOPEname! Sorry for the delay in adding these site. I've been a bit busy lately and it seems that the other contributors here have also been vacant.

Thank you very much for your submissions. They help us is the fight to end illegal file sharing of Minecraft mods. :-) If you find anything else, feel free to open more tickets, and we'll take a look!
