### ISSUE TITLE
minecraft-france.fr

### ISSUE THREAD

**Issue by Robijnvogel** [VictiniX888/Illegal-Mod-Sites#95]
https://www.minecraft-france.fr
They are crediting the author
They do link to CurseForge
However, they put CurseForge behind an addf.ly link, which just blamishes the name of mod authors, because we all know that addf.ly is terrible.

**Comment by bilde2910** [comment]
Hi, @Robijnvogel! I reviewed the site, but I find no evidence of reuploads or adfly linking on the site, Those that I found that were using ad linking services seemed to be using the same links as on their official sites or forum threads.

If you have any specific examples, feel free to reopen this issue, but for now, the site will not be added to the list. Thank you for your submission, though!

**Comment by Robijnvogel** [comment]
Shame on **me** for not checking if the adf.ly links were used by the original author...
I'm sorry for wasting your time.

**Comment by bilde2910** [comment]
Don't be sorry! We're verifying all submitted sites either way. It's better to have a few extra false reports than to miss out on real threats. Thanks for taking your time to submit a report :-)On May 1, 2017 20:05, Mathijs Riezebos <notifications@github.com> wrote:Shame on me for not checking if the adf.ly links were used by the original author...
I'm sorry for wasting your time.
