### ISSUE TITLE
planetaminecraft.com

### ISSUE THREAD

**Issue by royalcolorwaifu** [VictiniX888/Illegal-Mod-Sites#96]
tried looking for a 1.2.5 version of vazkii's health bar mod, came across this site
contacted vazkii later and was told a 1.2.5 version doesnt exist

**Comment by bilde2910** [comment]
Redistribution and adfly-skipping was found on this site. I'll add it. It also prevents usage without ad blockers, even though there does not appear to be any ads on the site. Thank you for your submission!

**Comment by EmanYm** [comment]
Are we talking about the same [PMC](https://www.planetminecraft.com/) here?
Any time I have downloaded something from PMC I look at other sources (like curse/curseforge and MCF) to check for the same poster, compare the list of projects/uploads, and finally download links.  Not once have I found anything that was not legit.
