### ISSUE TITLE
New Entry: MinecraftOre

### ISSUE THREAD

**Issue by willies952002** [VictiniX888/Illegal-Mod-Sites#99]
MinecraftOre, upon inspection of their site, seems to be doing the following 2 things:
- Distributing Mojang's intellectual property (such as a complete .minecraft folder with mods pre-installed)
- Distributing Mod Creator's intellectual property without permission

If this image doesn't say it enough, their download site is also red-flagged in Chrome as being an attack site: ![Image](https://i.domnian.com/f1b6ae8f.png)

**Comment by bilde2910** [comment]
This definitely goes on the list. Contains malicious software and redistributes mods and Mojang property. Thanks for the report!
